# SPDX-FileCopyrightText: 2019 yuzu Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: merge
  displayName: 'merge'
  jobs:
  - template: ./templates/merge.yml
